### ISSUE TITLE
Question about data setup

### ISSUE THREAD

**Issue by yunhaif** [Ram81/habitat-imitation-baselines#1]
Hi there,
I noted that you suggested to verify data setup by running
```
python examples/objectnav_replay.py --path data/datasets/objectnav/objectnav_mp3d_70k/sample/sample.json.gz
```
However, I didn't find the split named `sample` in the `objectnav_mp3d_70k` dataset downloaded from the provided link:
https://habitat-on-web.s3.amazonaws.com/release/datasets/objectnav/objectnav_mp3d_70k.zip
It seems there's only the `train` split.

Meanwhile, I got the following error when I replaced `sample` by `train` in the command above:
```
Traceback (most recent call last):
  File "examples/objectnav_replay.py", line 83, in <module>
    main()
  File "examples/objectnav_replay.py", line 78, in main
    output_prefix=args.output_prefix
  File "examples/objectnav_replay.py", line 18, in run_reference_replay
    with habitat.Env(cfg) as env:
  File "/home/xxx/habitat-imitation-baselines/habitat/core/env.py", line 80, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/home/xxx/habitat-imitation-baselines/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/home/xxx/habitat-imitation-baselines/habitat/datasets/object_nav/object_nav_dataset.py", line 93, in __init__
    super().__init__(config)
  File "/home/xxx/habitat-imitation-baselines/habitat/datasets/pointnav/pointnav_dataset.py", line 116, in __init__
    self.from_json(f.read(), scenes_dir=config.SCENES_DIR)
  File "/home/xxx/habitat-imitation-baselines/habitat/datasets/object_nav/object_nav_dataset.py", line 161, in from_json
    episode.goals = self.goals_by_category[episode.goals_key]
KeyError: '1LXtFkjw3qL.glb_game_equipment'
```

**Comment by Ram81** [comment]
Hi @fyhMer,

> However, I didn't find the split named sample in the objectnav_mp3d_70k dataset downloaded from the provided link:
https://habitat-on-web.s3.amazonaws.com/release/datasets/objectnav/objectnav_mp3d_70k.zip
It seems there's only the train split.

Sorry about the inconvenience. I have updated the released version of the dataset to include a sample split which can be used to sanity test the code setup. Let me know if you are still facing issues after downloading the latest dataset from the same link.

>Meanwhile, I got the following error when I replaced sample by train in the command above:

Thanks for pointing out the issue. The replay script was using incorrect config file which caused the above error. I have fixed the issue in [this commit](https://github.com/Ram81/habitat-imitation-baselines/commit/e94ed1f6c9141def262bfcacf4dc3a84c7b8d0fc). Can you try rebasing your copy with the latest master branch and try again? Let me know if the issue persists.

**Comment by yunhaif** [comment]
It works now. Many thanks!
