### ISSUE TITLE
Question about training the objectnav task.

### ISSUE THREAD

**Issue by me-no-money** [Ram81/habitat-imitation-baselines#12]
Hi, Ram.Thanks for the source code.
I have successfully run the `examples/objectnav_replay.py`. But when I attempt to train the objectnav task. I got the following error. It seems like the task had been through a lot of training epoch, but it can't find the file path when loading the object assets.
```
2023-03-31 10:57:13,046 update: 670     fps: 15.565     loss: 0.476
2023-03-31 10:57:13,048 update: 670     env-time: 227.618s      pth-time: 453.639s      frames: 10736
2023-03-31 10:57:13,048 Average window size: 50  reward: 10.429  distance_to_goal: 0.036  success: 1.000  spl: 0.471  softspl: 0.469  goal_vis_pixels: 0.003
W0331 10:57:14.335494 1855275 PathFinder.cpp:716] Building naavmesh before << -1 -- [4.75703,2.67878,2.88662]
W0331 10:57:14.335537 1855275 PathFinder.cpp:721] Building naavmesh  after << -1 -- [4.75703,2.67878,2.88662]
I0331 10:57:14.335543 1855275 PathFinder.cpp:407] Building navmesh with 327x166 cells
I0331 10:57:14.425912 1855275 PathFinder.cpp:675] Created navmesh with 252 vertices 120 polygons
I0331 10:57:14.425937 1855275 Simulator.cpp:767] reconstruct navmesh successful
W0331 10:57:21.601061 1855275 PathFinder.cpp:716] Building naavmesh before << -1 -- [4.75703,2.67878,2.88662]
W0331 10:57:21.601104 1855275 PathFinder.cpp:721] Building naavmesh  after << -1 -- [4.75703,2.67878,2.88662]
I0331 10:57:21.601111 1855275 PathFinder.cpp:407] Building navmesh with 327x166 cells
I0331 10:57:21.692174 1855275 PathFinder.cpp:675] Created navmesh with 252 vertices 120 polygons
I0331 10:57:21.692203 1855275 Simulator.cpp:767] reconstruct navmesh successful
2023-03-31 10:57:23,353 update: 680     fps: 15.564     loss: 0.360
2023-03-31 10:57:23,356 update: 680     env-time: 231.075s      pth-time: 460.462s      frames: 10896
2023-03-31 10:57:23,356 Average window size: 50  reward: 9.412  distance_to_goal: 0.029  success: 1.000  spl: 0.415  softspl: 0.413  goal_vis_pixels: 0.002
I0331 10:57:33.551846 1855275 PhysicsManager.cpp:33] Deconstructing PhysicsManager
I0331 10:57:33.551889 1855275 SemanticScene.h:41] Deconstructing SemanticScene
I0331 10:57:33.555999 1855275 SceneManager.h:25] Deconstructing SceneManager
I0331 10:57:33.556010 1855275 SceneGraph.h:26] Deconstructing SceneGraph
I0331 10:57:33.556727 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:33.556947 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:33.557231 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:33.557246 1855275 SceneGraph.h:26] Deconstructing SceneGraph
I0331 10:57:33.562839 1855275 Renderer.cpp:34] Deconstructing Renderer
I0331 10:57:33.562855 1855275 WindowlessContext.h:17] Deconstructing WindowlessContext
I0331 10:57:33.567837 1855275 MetadataMediator.cpp:63] MetadataMediator::setActiveSceneDatasetName : Old active dataset default changed to default successfully.
W0331 10:57:33.568241 1855275 Simulator.cpp:91] Downsampling by : 0
I0331 10:57:33.568300 1855275 PhysicsAttributesManager.cpp:27] File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
I0331 10:57:33.568317 1855275 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.glb changed to proposed JSON configuration filename : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.stage_config.json
I0331 10:57:33.567837 1855275 MetadataMediator.cpp:63] MetadataMediator::setActiveSceneDatasetName : Old active dataset default changed to default successfully.
W0331 10:57:33.568241 1855275 Simulator.cpp:91] Downsampling by : 0
I0331 10:57:33.568300 1855275 PhysicsAttributesManager.cpp:27] File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
I0331 10:57:33.568317 1855275 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.glb changed to proposed JSON configuration filename : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.stage_config.json
I0331 10:57:33.568404 1855275 AbstractObjectAttributesManagerBase.h:180] File (data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.glb) exists but is not a recognized config filename extension, so new default Stage attributes created and registered.
I0331 10:57:33.568413 1855275 Simulator.cpp:156] Loading navmesh from data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.navmesh
I0331 10:57:33.568756 1855275 Simulator.cpp:158] Loaded.
I0331 10:57:33.568768 1855275 SceneGraph.h:93] Created DrawableGroup: 
Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 510.47.03
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I0331 10:57:33.573024 1855275 ResourceManager.cpp:205] ResourceManager::loadStage : Loading Semantic Stage mesh : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r_semantic.ply
I0331 10:57:33.573035 1855275 SceneGraph.h:93] Created DrawableGroup: 
I0331 10:57:46.261307 1855275 ResourceManager.cpp:237] ResourceManager::loadStage : Semantic Stage mesh : data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r_semantic.ply loaded.
I0331 10:57:46.261370 1855275 ResourceManager.cpp:1146] Importing Basis files as BC3
I0331 10:57:51.785542 1855275 simulator.py:220] Loaded navmesh data/scene_datasets/mp3d/1pXnuDYAj8r/1pXnuDYAj8r.navmesh
I0331 10:57:51.786936 1855275 simulator.py:232] Recomputing navmesh for agent's height 0.88 and radius 0.18.
W0331 10:57:51.813958 1855275 PathFinder.cpp:716] Building naavmesh before << -1 -- [19.2872,6.33528,12.9889]
W0331 10:57:51.814005 1855275 PathFinder.cpp:721] Building naavmesh  after << -1 -- [19.2872,6.33528,12.9889]
I0331 10:57:51.814011 1855275 PathFinder.cpp:407] Building navmesh with 394x509 cells
I0331 10:57:52.105038 1855275 PathFinder.cpp:675] Created navmesh with 1097 vertices 543 polygons
I0331 10:57:52.105103 1855275 Simulator.cpp:767] reconstruct navmesh successful
W0331 10:57:52.134897 1855275 PathFinder.cpp:716] Building naavmesh before << -1 -- [19.2872,6.33528,12.9889]
W0331 10:57:52.134948 1855275 PathFinder.cpp:721] Building naavmesh  after << -1 -- [19.2872,6.33528,12.9889]
I0331 10:57:52.134954 1855275 PathFinder.cpp:407] Building navmesh with 394x509 cells
I0331 10:57:52.423643 1855275 PathFinder.cpp:675] Created navmesh with 1097 vertices 543 polygons
I0331 10:57:52.423698 1855275 Simulator.cpp:767] reconstruct navmesh successful
I0331 10:57:52.424098 1855275 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl changed to proposed JSON configuration filename : data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl.object_config.json
W0331 10:57:52.424120 1855275 AttributesManagerBase.h:198] AttributesManager::loadAllConfigsFromPath : Parsing Object : Cannot find data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl or data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl.object_config.json. Aborting parse.
I0331 10:57:52.424495 1855275 PhysicsManager.cpp:33] Deconstructing PhysicsManager
I0331 10:57:52.424515 1855275 SemanticScene.h:41] Deconstructing SemanticScene
I0331 10:57:52.429703 1855275 SceneManager.h:25] Deconstructing SceneManager
I0331 10:57:52.429718 1855275 SceneGraph.h:26] Deconstructing SceneGraph
I0331 10:57:52.430320 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:52.430545 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:52.431123 1855275 Sensor.h:87] Deconstructing Sensor
I0331 10:57:52.431138 1855275 SceneGraph.h:26] Deconstructing SceneGraph
I0331 10:57:52.453112 1855275 Renderer.cpp:34] Deconstructing Renderer
I0331 10:57:52.453145 1855275 WindowlessContext.h:17] Deconstructing WindowlessContext
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/lq/anaconda3/envs/habitat-web/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lq/anaconda3/envs/habitat-web/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lq/anaconda3/envs/habitat-web/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lq/habitat-web-baselines/habitat/core/vector_env.py", line 208, in _worker_env
    observations = env.reset()
  File "/home/lq/habitat-web-baselines/habitat_baselines/common/environments.py", line 57, in reset
    observations = super().reset()
  File "/home/lq/anaconda3/envs/habitat-web/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lq/habitat-web-baselines/habitat/core/env.py", line 408, in reset
    return self._env.reset()
  File "/home/lq/habitat-web-baselines/habitat/core/env.py", line 222, in reset
    self.reconfigure(self._config)
  File "/home/lq/habitat-web-baselines/habitat/core/env.py", line 346, in reconfigure
    self._sim.reconfigure(self._config.SIMULATOR)
  File "/home/lq/habitat-web-baselines/habitat/sims/habitat_simulator/habitat_simulator.py", line 349, in reconfigure
    self._initialize_THDA_scene()
  File "/home/lq/habitat-web-baselines/habitat/sims/habitat_simulator/habitat_simulator.py", line 401, in _initialize_THDA_scene
    ), f"Object template '{object_template}' wasn't found."
AssertionError: Object template 'data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl' wasn't found.
```
My data folder settings is as follows:
![dataset](https://user-images.githubusercontent.com/71805391/229124352-7bb62865-804a-4524-a94f-989432fe9aa7.png)
What have I missed? And could you tell me how to solve it?

**Comment by Ram81** [comment]
Hi @me-no-money , are you using the `objectnav_mp3d_gibson_80k.zip` dataset?

**Comment by me-no-money** [comment]
Hi @Ram81, thanks for your reply. I'm using the objectnav_mp3d_70k.zip dataset. BTW, I can't download the objectnav_mp3d_gibson_80k.json.gz dataset from this link [objectnav_mp3d_gibson_80k.json.gz](https://habitat-on-web.s3.amazonaws.com/release/datasets/objectnav/objectnav_mp3d_gibson_80k.zip) . Should I use the objectnav_mp3d_gibson_80k.zip dataset?

**Comment by yuerbujin** [comment]
hello @Ram81,
i'm also facing the exact same issue. could u please help me out.

**Comment by Ram81** [comment]
@me-no-money @yuerbujin can you try downloading the YCB object dataset for habitat-sim using the instructions mentioned [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#ycb-benchmarks---object-and-model-set). Please make sure that dataset is downloaded at `data/assets/objects/ycb_google_16k_v2/configs_gltf/`. Let me know if this resolves the issue you are facing.

**Comment by yuerbujin** [comment]
> @me-no-money @yuerbujin can you try downloading the YCB object dataset for habitat-sim using the instructions mentioned [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#ycb-benchmarks---object-and-model-set). Please make sure that dataset is downloaded at `data/assets/objects/ycb_google_16k_v2/configs_gltf/`. Let me know if this resolves the issue you are facing.

thank you so much for you quick reply.
In which file did you specify this directory "data/assets/objects/ycb_google_16k_v2/configs_gltf/", i want to modify it.

**Comment by yuerbujin** [comment]
> @me-no-money @yuerbujin can you try downloading the YCB object dataset for habitat-sim using the instructions mentioned [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#ycb-benchmarks---object-and-model-set). Please make sure that dataset is downloaded at `data/assets/objects/ycb_google_16k_v2/configs_gltf/`. Let me know if this resolves the issue you are facing.

thank you so much for you quick response. i have solved this problem!

**Comment by me-no-money** [comment]
Hi!  @yuerbujin, Can you share the directory structure in your data/assets/objects/ycb_google_16k_v2/configs_gltf/ folder? Is data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl a folder? Which has the .object_config.json file and the .glb file? Or the directory
 structure should be data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl.object_config.json?

**Comment by me-no-money** [comment]
> @me-no-money @yuerbujin can you try downloading the YCB object dataset for habitat-sim using the instructions mentioned [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#ycb-benchmarks---object-and-model-set). Please make sure that dataset is downloaded at `data/assets/objects/ycb_google_16k_v2/configs_gltf/`. Let me know if this resolves the issue you are facing.

@Ram81  Thank u! I have already solved this problem too!

**Comment by Ram81** [comment]
Closing this issue as it is resolved.

**Comment by BigTree765** [comment]
@me-no-money  @Ram81  @yuerbujin  I am  facing the same issue,  Did you try solving it using the following instructions:

python -m habitat_sim.utils.datasets_download --uids ycb --data-path data/assets/objects/ycb_google_16k_v2/configs_gltf/
After running this command, I encountered the same issue. My dataset is configured as follows:
![image](https://github.com/Ram81/habitat-imitation-baselines/assets/44998403/00a1a9d0-ad8a-4709-be91-f8c2c90a57ea)

**Comment by djiajunustc** [comment]
@yusirhhh I have met the same problem as yours. Have you addressed it?

**Comment by yvfengZhong** [comment]
Hello,

I wanted to share some insights regarding the ycb_google_16k_v2 directory setup. It appears that this directory corresponds directly to the ycb directory, and the ycb_google_16k_v2/configs_gltf aligns with the ycb/configs directory. Here's how you can set it up:

Linking and Renaming the Directory:

After downloading the YCB dataset, you can link the ycb directory to the data/assets/objects directory and rename it to ycb_google_16k_v2.
Renaming the Configs Directory:

Within the ycb directory, rename the configs directory to configs_gltf.
No Need to Alter Other Directories:

The collision_meshes and meshes directories can remain unchanged.
I hope this helps streamline your setup process. If anyone else has further insights or suggestions, feel free to add!
