### ISSUE TITLE
Ran out of Memory while loading pick_place_12k.zip 

### ISSUE THREAD

**Issue by kpant14** [Ram81/habitat-imitation-baselines#4]
I am currently running this script on a PC with 32GB RAM. But when I try to visualize the data using examples/pick_place_replay.py, my PC runs out of memory. Could you please let me know the recommended system configuration?

**Comment by kpant14** [comment]
[UPDATE] I ran this code in the server with 128GB RAM. While loading the data I observed a whopping 80GB RAM utilization while loading the data. Now, I ran into another error:

```
python examples/pickplace_replay.py --path data/datasets/pick_place/pick_place_12k/train/train.json.gz 
2022-07-08 19:33:45,369 Initializing dataset PickPlaceDataset-v1
2022-07-08 19:42:27,518 initializing sim PickPlaceSim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0708 19:42:27.521371 640966 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : default changed to proposed JSON configuration filename : default.scene_dataset_config.json
I0708 19:42:27.521478 640966 AssetAttributesManager.cpp:117] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
I0708 19:42:27.521509 640966 AssetAttributesManager.cpp:117] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I0708 19:42:27.521536 640966 AssetAttributesManager.cpp:117] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
I0708 19:42:27.521553 640966 AssetAttributesManager.cpp:117] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I0708 19:42:27.521564 640966 AssetAttributesManager.cpp:117] Asset attributes (cubeSolid : cubeSolid) created and registered.
I0708 19:42:27.521572 640966 AssetAttributesManager.cpp:117] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I0708 19:42:27.521593 640966 AssetAttributesManager.cpp:117] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
I0708 19:42:27.521628 640966 AssetAttributesManager.cpp:117] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I0708 19:42:27.521639 640966 AssetAttributesManager.cpp:117] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I0708 19:42:27.521651 640966 AssetAttributesManager.cpp:117] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I0708 19:42:27.521665 640966 AssetAttributesManager.cpp:117] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I0708 19:42:27.521679 640966 AssetAttributesManager.cpp:117] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I0708 19:42:27.521687 640966 AssetAttributesManager.cpp:105] AssetAttributesManager::buildCtorFuncPtrMaps : Built default primitive asset templates : 12
W0708 19:42:27.521734 640966 ObjectAttributesManager.cpp:175] object template: capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false
W0708 19:42:27.521772 640966 ObjectAttributesManager.cpp:175] object template: capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1
W0708 19:42:27.521807 640966 ObjectAttributesManager.cpp:175] object template: coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true
W0708 19:42:27.521840 640966 ObjectAttributesManager.cpp:175] object template: coneWireframe_segments_32_halfLen_1.25
W0708 19:42:27.521873 640966 ObjectAttributesManager.cpp:175] object template: cubeSolid
W0708 19:42:27.521903 640966 ObjectAttributesManager.cpp:175] object template: cubeWireframe
W0708 19:42:27.521935 640966 ObjectAttributesManager.cpp:175] object template: cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true
W0708 19:42:27.521967 640966 ObjectAttributesManager.cpp:175] object template: cylinderWireframe_rings_1_segments_32_halfLen_1
W0708 19:42:27.521998 640966 ObjectAttributesManager.cpp:175] object template: icosphereSolid_subdivs_1
W0708 19:42:27.522030 640966 ObjectAttributesManager.cpp:175] object template: icosphereWireframe_subdivs_1
W0708 19:42:27.522061 640966 ObjectAttributesManager.cpp:175] object template: uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false
W0708 19:42:27.522092 640966 ObjectAttributesManager.cpp:175] object template: uvSphereWireframe_rings_16_segments_32
I0708 19:42:27.522143 640966 SceneDatasetAttributesManager.cpp:23] File (default) not found, so new default dataset attributes created and registered.
I0708 19:42:27.522147 640966 MetadataMediator.cpp:54] MetadataMediator::createDataset : Dataset default successfully created.
W0708 19:42:27.525544 640966 Simulator.cpp:91] Downsampling by : 0
I0708 19:42:27.525563 640966 PhysicsAttributesManager.cpp:27] File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
I0708 19:42:27.525570 640966 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : data/scene_datasets/mp3d/JeFG25nYj2p.glb changed to proposed JSON configuration filename : data/scene_datasets/mp3d/JeFG25nYj2p.stage_config.json
I0708 19:42:27.525624 640966 AbstractObjectAttributesManagerBase.h:180] File (data/scene_datasets/mp3d/JeFG25nYj2p.glb) exists but is not a recognized config filename extension, so new default Stage attributes created and registered.
I0708 19:42:27.525633 640966 Simulator.cpp:156] Loading navmesh from data/scene_datasets/mp3d/JeFG25nYj2p.navmesh
I0708 19:42:27.525804 640966 Simulator.cpp:158] Loaded.
I0708 19:42:27.525818 640966 SceneGraph.h:93] Created DrawableGroup: 
Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 510.54
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I0708 19:42:27.608045 640966 ResourceManager.cpp:247] ResourceManager::loadStage : Not loading semantic mesh
I0708 19:42:27.608069 640966 ResourceManager.cpp:1146] Importing Basis files as BC3
W0708 19:42:28.765156 640966 Simulator.cpp:248] :
---
 The active scene does not contain semantic annotations. 
---
I0708 19:42:28.804448 640966 simulator.py:220] Loaded navmesh data/scene_datasets/mp3d/JeFG25nYj2p.navmesh
2022-07-08 19:42:28,806 Initializing task PickPlaceTask-v0
Traceback (most recent call last):
  File "examples/pickplace_replay.py", line 90, in <module>
    main()
  File "examples/pickplace_replay.py", line 86, in main
    output_prefix=args.output_prefix
  File "examples/pickplace_replay.py", line 16, in run_reference_replay
    with habitat.Env(cfg) as env:
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/core/env.py", line 117, in __init__
    dataset=self._dataset,
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/tasks/registration.py", line 22, in make_task
    return _task(**kwargs)
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/tasks/pickplace/pickplace.py", line 1389, in __init__
    super().__init__(**kwargs)
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/core/embodied_task.py", line 249, in __init__
    entities_config=config,
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/core/embodied_task.py", line 277, in _init_entities
    task=self,
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/tasks/pickplace/pickplace.py", line 291, in __init__
    super().__init__(config=config)
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/core/simulator.py", line 76, in __init__
    self.observation_space = self._get_observation_space(*args, **kwargs)
  File "/home/corallab-s1/Kartik/habitat-web-baselines/habitat/tasks/pickplace/pickplace.py", line 295, in _get_observation_space
    len(self._sim.get_existing_object_ids())
  File "/home/corallab-s1/anaconda3/envs/habitat-web/lib/python3.6/site-packages/gym/spaces/discrete.py", line 37, in __init__
    assert n > 0, "n (counts) have to be positive"
AssertionError: n (counts) have to be positive
I0708 19:45:12.129606 640966 PhysicsManager.cpp:33] Deconstructing PhysicsManager
I0708 19:45:12.129635 640966 SemanticScene.h:41] Deconstructing SemanticScene
I0708 19:45:12.131809 640966 SceneManager.h:25] Deconstructing SceneManager
I0708 19:45:12.131819 640966 SceneGraph.h:26] Deconstructing SceneGraph
I0708 19:45:12.132238 640966 Sensor.h:87] Deconstructing Sensor
I0708 19:45:12.132259 640966 Sensor.h:87] Deconstructing Sensor
I0708 19:45:12.134022 640966 Renderer.cpp:34] Deconstructing Renderer
I0708 19:45:12.134043 640966 WindowlessContext.h:17] Deconstructing WindowlessContext
I0708 19:45:12.135520 640966 Simulator.cpp:47] Deconstructing Simulator
```


I think the objects are not getting initialized in the simulator. Do I need to download object dataset as well?

**Comment by Ram81** [comment]
Hi @kpant14 , yes the full Pick-and-Place dataset requires larger memory machines as it stores state of all objects, actions, sensors and agent at every step for replay. For faster replay you can try to create a small sample of the dataset with fewer episodes which will be faster to load. 

I'll also create a sample dataset split and release in next few days with documentation on how to download it in next few days for easier testing on low memory machine.

>I think the objects are not getting initialized in the simulator. Do I need to download object dataset as well?

Yes, you'll have to download object assets as well. You can download them by following [these steps](https://github.com/Ram81/habitat-imitation-baselines#downloading-object-assets). The object asset download instructions got missed in the original release.

Let me know if you are still facing issues after downloading the object assets.

**Comment by Ram81** [comment]
Hi @kpant14, I created a sample dataset in addition to our full 12k episode dataset and uploaded it [here](https://habitat-on-web.s3.amazonaws.com/release/datasets/pick_place/pick_place_12k.zip). You can use the dataset in the `sample` folder to test the setup with the replay script. Let me know if you run into any issues.
